openapi: 3.0.1
info:
  title: OQTOPUS Cloud User API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server url
paths:
  /devices:
    get:
      tags:
        - device
      summary: List available devices
      description: List available devices
      operationId: listDevices
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Returns a list of available devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/devices.DeviceInfo'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
  /devices/{deviceId}:
    get:
      tags:
        - device
      summary: Get specified device details
      description: get device
      operationId: getDevice
      security:
        - BearerAuth: []
      parameters:
        - name: deviceId
          in: path
          description: Device identifier
          required: true
          schema:
            type: string
          example: Kawasaki
      responses:
        '200':
          description: task response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices.DeviceInfo'
        '404':
          description: Device with deviceId not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
  /jobs:
    get:
      tags:
        - job
      summary: List all quantum jobs
      description: List all quantum jobs
      operationId: listJobs
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Return a list of submitted quantum jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/jobs.JobInfo'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
    post:
      tags:
        - job
      summary: Submit a quantum job
      description: Submit a quantum job
      operationId: submitJob
      security:
        - BearerAuth: []
      requestBody:
        description: Quantum job to be submitted
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobs.JobDef'
            examples:
              simulator:
                description: Simulator example
                value:
                  code: OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
                  name: Bell State Sampling
                  device: SVsim
                  nNodes: 12
                  nShots: 1000
                  skipTranspilation: false
                  seedTranspilation: 873
                  seedSimulation: 39058567
                  nPerNode: 2
                  simulationOpt:
                    optimizationMethod: light
                    optimizationBlockSize: 1
                    optimizationSwapLevel: 1
                  note: Bell State Sampling Example
              qpu:
                description: QPU example
                value:
                  code: OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
                  name: Bell State Sampling
                  device: Kawasaki
                  nShots: 1000
                  note: Bell State Sampling Example
      responses:
        '200':
          description: Job submitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.SubmitJobResponse'
              example:
                jobId: 7af020f6-2e38-4d70-8cf0-4349650ea08c
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                detail: Bad request malformed input data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
  /jobs/{jobId}:
    get:
      tags:
        - job
      summary: Get selected job
      description: Get selected job
      operationId: getSamplingJob
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          description: Job identifier
          schema:
            type: string
      responses:
        '200':
          description: Return quantum job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.JobInfo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                detail: Bad request malformed input data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                detail: job not found
    delete:
      tags:
        - job
      summary: Delete job
      description: 'Deletes quantum job and related result<br/><br/>Operation is valid only for job with status: COMPLETED, FAILED and CANCELLED. QUEUED and RUNNING jobs must be cancelled before deletion.'
      operationId: deleteSamplingJob
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          description: Job identifier
          schema:
            type: string
      responses:
        '200':
          description: Quantum job deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success.SuccessResponse'
              example:
                message: Quantum job deleted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                detail: Bad request malformed input data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                detail: job not found
  /jobs/{jobId}/status:
    get:
      tags:
        - job
      summary: Get selected job's status
      description: Get selected job's status
      operationId: getSamplingJobStatus
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          description: Job identifier
          schema:
            type: string
      responses:
        '200':
          description: Return quantum job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.GetJobStatusResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                detail: Bad request malformed input data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                detail: job not found
  /jobs/{jobId}/cancel:
    post:
      tags:
        - job
      summary: Cancel job
      description: 'Start a procedure to cancel quantum job.<br/><br/> Operation is valid only for job with status: QUEUED or RUNNING.'
      operationId: cancelSamplingJob
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: jobId
          required: true
          description: Job identifier
          schema:
            type: string
      responses:
        '200':
          description: Job cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success.SuccessResponse'
              example:
                message: cancel request accepted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                detail: Bad request malformed input data
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                detail: Unauthorized
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                detail: job not found
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    devices.CalibrationData:
      description: Calibration data available only for 'QPU' devices
      type: object
      properties:
        qubitConnectivity:
          type: array
          items:
            type: string
            format: (number, number)
          example:
            - (1,4)
            - (4,5)
            - (5,8)
        t1:
          type: object
          additionalProperties:
            type: number
            format: float
          example:
            '0': 55.51
            '1': 37.03
            '2': 57.13
        t2:
          type: object
          additionalProperties:
            type: number
            format: float
          example:
            '0': 99.31
            '1': 111.03
            '2': 30.12
        roError:
          type: object
          additionalProperties:
            type: number
            format: float
          example:
            '0': 0.0467
            '1': 0.18
            '2': 0.355
        gateError:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: number
              format: float
          example:
            sx:
              '0': 0.00692
              '1': 0.00296
              '2': 0.072
        measProb0As1:
          type: object
          additionalProperties:
            type: number
            format: float
          example:
            '0': 0.00608
            '1': 0.012
            '2': 0.248
        measProb1As0:
          type: object
          additionalProperties:
            type: number
            format: float
          example:
            '0': 0.0281
            '1': 0.386
            '2': 0.0811
        gateDuration:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: number
              format: float
          example:
            sx:
              '0': 29.3
              '1': 50.9
              '2': 45.4
    devices.DeviceInfo:
      type: object
      properties:
        deviceId:
          type: string
          example: SVSim
        deviceType:
          type: string
          enum:
            - QPU
            - simulator
          example: simulator
        status:
          type: string
          enum:
            - AVAILABLE
            - NOT_AVAILABLE
          example: AVAILABLE
        restartAt:
          description: Parameter mandatory and valid for 'NOT_AVAILABLE' devices
          type: string
          format: date-time
          example: '2022-10-19T11:45:34+09:00'
        nPendingTasks:
          type: integer
          example: 8
        nQubits:
          type: integer
          example: 39
        nNodes:
          description: Parameter valid only for 'simulator' devices
          type: integer
          example: 512
        basisGates:
          type: array
          items:
            type: string
          example:
            - x
            - 'y'
            - z
            - h
            - s
            - sdg
            - t
            - tdg
            - rx
            - ry
            - rz
            - cx
            - cz
            - swap
            - u1
            - u2
            - u3
            - u
            - p
            - id
            - sx
            - sxdg
        supportedInstructions:
          type: array
          items:
            type: string
          example:
            - measure
            - barrier
            - reset
        calibrationData:
          $ref: '#/components/schemas/devices.CalibrationData'
        calibratedAt:
          description: Parameter available only for 'QPU' devices with available calibration data
          type: string
          format: date-time
          example: '2022-10-19T11:45:34+09:00'
        description:
          type: string
          example: State vector-based quantum circuit simulator
      required:
        - deviceId
        - deviceType
        - status
        - nPendingTasks
        - basisGates
        - supportedInstructions
        - description
      example:
        - deviceId: SVSim
          deviceType: simulator
          status: AVAILABLE
          nPendingTasks: 8
          nQubits: 39
          nNodes: 512
          basisGates:
            - x
            - 'y'
            - z
            - h
            - s
            - sdg
            - t
            - tdg
            - rx
            - ry
            - rz
            - cx
            - cz
            - swap
            - u1
            - u2
            - u3
            - u
            - p
            - id
            - sx
            - sxdg
          supportedInstructions:
            - measure
            - barrier
            - reset
          description: State vector-based quantum circuit simulator
    error.UnauthorizedError:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
    error.InternalServerError:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
    error.NotFoundError:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
    jobs.JobId:
      type: string
      format: uuid
      example: 7af020f6-2e38-4d70-8cf0-4349650ea08c
    jobs.JobStatus:
      type: string
      enum:
        - submitted
        - ready
        - running
        - success
        - failed
        - cancelled
      example: submitted
    jobs.JobInfo:
      type: object
      properties:
        jobId:
          $ref: '#/components/schemas/jobs.JobId'
        code:
          type: string
          example: OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
        name:
          type: string
          example: Bell State Sampling
        device:
          type: string
          example: Kawasaki
        nQubits:
          description: Parameter exclusive with nNodes
          type: integer
        nNodes:
          description: Parameter exclusive with nQubits<br/>Parameter valid only for 'simulator' devices
          type: integer
          example: 12
        nShots:
          type: integer
          minimum: 1
          maximum: 10000000
          example: '1000'
        qubitAllocation:
          description: Parameter valid only for QPU devices
          type: object
          additionalProperties:
            type: integer
          example:
            '0': 12
            '1': 16
        skipTranspilation:
          type: boolean
          example: false
        seedTranspilation:
          description: Parameter valid only if skipTranspilation is false
          type: integer
          example: 873
        seedSimulation:
          description: Parameter valid only for 'simulator' devices
          type: integer
          example: 39058567
        roErrorMitigation:
          description: Parameter valid only for QPU devices
          type: string
          enum:
            - none
            - pseudo_inverse
            - least_square
          example: pseudo_inverse
        nPerNode:
          description: Parameter valid only for simulator devices
          type: integer
          minimum: 1
          example: 5
        simulationOpt:
          description: Parameter valid only for simulator devices
          type: object
          example:
            optimizationMethod: light
            optimizationBlockSize: 1
            optimizationSwapLevel: 1
        note:
          type: string
          example: Bell State Sampling Example
        status:
          $ref: '#/components/schemas/jobs.JobStatus'
        createdAt:
          type: string
          format: date-time
          example: '2022-10-19T11:45:34+09:00'
      required:
        - jobId
        - code
        - device
        - nShots
        - skipTranspilation
        - status
        - createdAt
      example:
        jobId: 7af020f6-2e38-4d70-8cf0-4349650ea08c
        code: OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
        name: Bell State Sampling
        device: Kawasaki
        nNodes: 12
        nShots: 1000
        skipTranspilation: false
        seedTranspilation: 387
        seedSimulation: 39058567
        nPerNode: 2
        simulationOpt:
          optimizationMethod: light
          optimizationBlockSize: 1
          optimizationSwapLevel: 1
        note: Bell State Sampling Example
        status: submitted
        createdAt: '2022-10-19T11:45:34+09:00'
    jobs.JobDef:
      type: object
      properties:
        code:
          type: string
          example: OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
        name:
          type: string
          example: Bell State Sampling
        device:
          type: string
          example: Kawasaki
        nQubits:
          description: Parameter exclusive with nNodes
          type: integer
        nNodes:
          description: Parameter exclusive with nQubits<br/>Parameter valid only for 'simulator' devices
          type: integer
          example: 12
        nShots:
          type: integer
          minimum: 1
          maximum: 10000000
          example: '1000'
        qubitAllocation:
          description: Parameter valid only for QPU devices
          type: object
          additionalProperties:
            type: integer
          example:
            '0': 12
            '1': 16
        skipTranspilation:
          type: boolean
          default: false
          example: false
        seedTranspilation:
          description: Parameter valid only if skipTranspilation is false
          type: integer
          example: 873
        seedSimulation:
          description: Parameter valid only for 'simulator' devices
          type: integer
          example: 39058567
        roErrorMitigation:
          description: Parameter valid only for QPU devices
          type: string
          enum:
            - none
            - pseudo_inverse
            - least_square
          default: none
          example: pseudo_inverse
        nPerNode:
          description: Parameter valid only for simulator devices
          type: integer
          minimum: 1
          example: 5
        simulationOpt:
          description: Parameter valid only for simulator devices
          type: object
          example:
            optimizationMethod: light
            optimizationBlockSize: 1
            optimizationSwapLevel: 1
        note:
          type: string
          example: Bell State Sampling Example
      required:
        - code
        - device
        - nShots
    jobs.SubmitJobResponse:
      description: submit a job
      type: object
      properties:
        jobId:
          $ref: '#/components/schemas/jobs.JobId'
      required:
        - jobId
    error.BadRequest:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
    success.SuccessResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    jobs.GetJobStatusResponse:
      description: job status
      type: object
      properties:
        jobId:
          $ref: '#/components/schemas/jobs.JobId'
        status:
          $ref: '#/components/schemas/jobs.JobStatus'
      required:
        - jobId
        - status
